version: '3.9'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      # Update .NET version here
        DOTNET_VERSION: ${DOTNET_VERSION:-7.0}
    image: sakiv77/devcontainer-dotnet:${DOTNET_VERSION:-7.0}
    ports:
      - 9922:22
    volumes:
      - type: bind
        source: .
        target: /workspace
    environment:
      DEV: true
    env_file: local.env